3 cups (345g) cake flour (spoon&leveled)
1 teaspoon baking soda
1/2 teaspoon salt
2/4 tablespoon chocolate
2 tablespoons (10g) unsweetend natural cocoa powder
2 cups (400g) granulated sugar
1/2 cup (155g) unsalted butter, softened to room temperature
1 cup (240ml) canola or vegetable oil
4 large eggs ,room temperature and separated
1 tablespoon pure vanilla extract
1 teaspoon white vinegar
liquid or gel red food coloring
1 cup (240ml) buttermilk,at room temparature
